baseURL = "https://hugo-theme-luna.imiku.me/"
languageCode = "en-us"
defaultContentLanguage = "en-us"
title = "Hugo Theme Luna"
enableRobotsTXT = true
enableEmoji = true
theme = "hugo-theme-luna"
timeout = 60_000
timeZone = "Asia/Jakarta"
enableGitInfo = false
hasCJKLanguage = true
paginate = 10
summaryLength = 70
canonifyURLs = false
relativeURLs = false

[permalinks]
posts = "/:year/:month/:day/:slug.html"
pages = "/:slug.html"

[author]
name = "Ice-Hazymoon"

[frontmatter]
lastmod = [
  ":git",
  "lastmod",
  ":fileModTime",
  "date",
  "publishDate",
  ":default"
]

[taxonomies]
tag = "tags"
category = "categories"

[imaging]
resampleFilter = "CatmullRom"
quality = 95
anchor = "smart"

[caches.getresource]
dir = ":resourceDir/_gen"
maxAge = "24h"

[privacy.googleAnalytics]
anonymizeIP = true
googleAnalytics = "G-J5DDYB6R2J"

[privacy.youtube]
privacyEnhanced = true

[sitemap]
changefreq = "weekly"
priority = 0.5
filename = "sitemap.xml"

[["$manuMain"]]
name = "Home"
weight = 10
identifier = "home"
url = "/"

  ["$manuMain".params]
  icon = "eva eva-home"

[["$manuMain"]]
name = "About"
weight = 20
identifier = "about"
url = "/about/"

  ["$manuMain".params]
  icon = "eva eva-heart"

[["$manuMain"]]
name = "Links"
weight = 30
identifier = "links"
url = "/links/"

  ["$manuMain".params]
  icon = "eva eva-people"

[["$manuMain"]]
name = "Archives"
weight = 40
identifier = "archives"
url = "/archives/"

  ["$manuMain".params]
  icon = "eva eva-bar-chart"

[["$manuMain"]]
name = "Tags"
weight = 50
identifier = "tags"
url = "/tags/"

  ["$manuMain".params]
  icon = "eva eva-hash"

[["$manuMain"]]
name = "Categories"
weight = 60
identifier = "categories"
url = "/categories/"

  ["$manuMain".params]
  icon = "eva eva-folder"

[["$manuMain"]]
name = "Twitter"
weight = 70
identifier = "twitter"
url = "/twitter/"

  ["$manuMain".params]
  icon = "eva eva-twitter"

[["$manuMain"]]
name = "GitHub"
weight = 80
identifier = "github"
url = "/github/"

  ["$manuMain".params]
  icon = "eva eva-github"

[["$manuMain"]]
name = "Search"
weight = 999
identifier = "search"
url = "/search/"

  ["$manuMain".params]
  icon = "eva eva-search"

[[menu.main]]
name = "Home"
weight = 10
identifier = "home"
url = "/"

  [menu.main.params]
  icon = "eva eva-home"

[[menu.main]]
name = "About"
weight = 20
identifier = "about"
url = "/about/"

  [menu.main.params]
  icon = "eva eva-heart"

[[menu.main]]
name = "Links"
weight = 30
identifier = "links"
url = "/links/"

  [menu.main.params]
  icon = "eva eva-people"

[[menu.main]]
name = "Archives"
weight = 40
identifier = "archives"
url = "/archives/"

  [menu.main.params]
  icon = "eva eva-bar-chart"

[[menu.main]]
name = "Twitter"
weight = 70
identifier = "twitter"
url = "/twitter/"

  [menu.main.params]
  icon = "eva eva-twitter"

[[menu.main]]
name = "GitHub"
weight = 80
identifier = "github"
url = "/github/"

  [menu.main.params]
  icon = "eva eva-github"

[[menu.main]]
name = "Search"
weight = 999
identifier = "search"
url = "/search/"

  [menu.main.params]
  icon = "eva eva-search"

[markup.highlight]
style = "dracula"
guessSyntax = true
tabWidth = 4
lineNumbersInTable = true
lineNos = true
codeFences = true

[markup.goldmark.renderer]
unsafe = true

[params]
publicCDN = ""
sitemap = true
themeColor = "#dd6065"
blackAndWhite = false
headlineCounter = true
fixedNav = false
font = 'Roboto, "Helvetica Neue", Helvetica, Arial, sans-serif'
since = "2016"
autoDarkMode = false
qrcodeAPI = "https://www.lofter.com/genBitmaxImage?url="
i18nlist = true
imageZoom = true
lazyload = true
googleTranslate = true
pangu = true
search = true
lastmod = true
readingTime = true
wordCount = false
pjax = true
pwa = true
katex = true
backtop = true
defaultFeaturedImage = false
author = "Ice-Hazymoon"
keywords = [ "Hugo", "Hugo Theme", "Luna" ]
description = "A simple, performance-first, SEO-friendly Hugo theme"

  [params.announcement]
  enabled = true
  file = "README.md"

  [params.comments]
  enabled = true
  provider = "giscus"

    [params.comments.giscus]
    repo = "Ice-Hazymoon/hugo-theme-luna"
    repoID = "R_kgDOHQOwYw"
    category = "Comments"
    categoryID = "DIC_kwDOHQOwY84CP0Sy"
    mapping = "title"
    reactionsEnabled = 1
    emitMetadata = 0
    lazy = false
    lang = "en"

  [params.rss]
  enabled = true
  fullText = true

  [params.console]
  enabled = true
  leftColor = "#dd6065"
  leftText = "Hugo Theme Luna"
  rightColor = "#feb462"
  rightText = "Powered by Hugo ❤ Luna"

  [params.customScript]
  enabled = false
  pjax = true

  [params.runTime]
  enabled = true
  creatTime = "2016/12/12"

  [params.outdatedInfoWarning]
  enabled = true
  day = 90

  [params.share]
  twitter = true
  facebook = true
  weibo = true
  copyLinkText = true
  qrcode = true

  [params.license]
  enabled = true
  name = "CC BY-NC-ND 4.0"
  icon = "Cc-by-nc-nd.svg"
  url = "https://creativecommons.org/licenses/by-nc-nd/4.0"

  [params.github]
  id = "torvalds"
  minStars = 5

  [params.twitter]
  rsshub = "https://rsshub.rssforever.com"
  id = "GenshinImpact"
  imageProcessing = true

  [params.bionicReading]
  enabled = true
  autoBionic = false
  skipLinks = false
  excludeWords = [ ]
  excludeNodeNames = [ ]
  excludeClasses = [ "github" ]

  [params.toc]
  enabled = true
  wordCount = 400

  [params.HugoEncrypt]
  Password = "123456"
  Storage = "session"

  [params.imageProcessing]
  cover = true
  content = true
  autoResize = [ 1_080, 1_440 ]
  webp = true

  [params.opengraph]
  image = "featured.png"

    [params.opengraph.twitter]
    cardType = "summary_large_image"
    site = "@Ice_Hazymoon"

[build]
noJSConfigInAssets = true

[languages.zh-cn]
contentDir = "content/zh-hans"
languageName = "中文"

  [languages.zh-cn.params]
  languageIcon = "images/i18n/zh-cn.svg"
  font = "Times New Roman,Times,Heti Song,serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol"

    [languages.zh-cn.params.twitter]
    rsshub = "https://rsshub.rssforever.com"
    id = "Ice_Hazymoon"
    imageProcessing = true

    [languages.zh-cn.params.github]
    id = "Ice-Hazymoon"
    minStars = 10

    [languages.zh-cn.params.license]
    enabled = true
    name = "署名 - 非商业性使用 - 禁止演绎 4.0"
    icon = "Cc-by-nc-nd.svg"
    url = "https://creativecommons.org/licenses/by-nc-nd/4.0/deed.zh"

    [languages.zh-cn.params.announcement]
    enabled = true
    file = "README.zh.md"

    [languages.zh-cn.params.comments]
    enabled = true
    provider = "giscus"

      [languages.zh-cn.params.comments.giscus]
      repo = "Ice-Hazymoon/hugo-theme-luna"
      repoID = "R_kgDOHQOwYw"
      category = "Comments"
      categoryID = "DIC_kwDOHQOwY84CP0Sy"
      mapping = "title"
      reactionsEnabled = 1
      emitMetadata = 0
      lazy = false
      lang = "zh-CN"

[languages.en-us]
contentDir = "content/en-us"
languageName = "English"

  [languages.en-us.params]
  languageIcon = "images/i18n/en-us.svg"

[languages.ja]
contentDir = "content/ja"
languageName = "日本語"

  [languages.ja.params]
  languageIcon = "images/i18n/ja.svg"
  font = "'-apple-system', BlinkMacSystemFont, 'Yu Gothic', '游ゴシック', YuGothic, '游ゴシック体', 'Noto Sans Japanese', 'ヒラギノ角ゴ Pro W3', 'メイリオ', 'Hiragino Kaku Gothic ProN', 'MS PGothic', Osaka, 'sans-serif'"

    [languages.ja.params.announcement]
    enabled = true
    file = "README.ja.md"

    [languages.ja.params.comments]
    enabled = true
    provider = "giscus"

      [languages.ja.params.comments.giscus]
      repo = "Ice-Hazymoon/hugo-theme-luna"
      repoID = "R_kgDOHQOwYw"
      category = "Comments"
      categoryID = "DIC_kwDOHQOwY84CP0Sy"
      mapping = "title"
      reactionsEnabled = 1
      emitMetadata = 0
      lazy = false
      lang = "ja"

[[languages.ja.menu.main]]
name = "Home"
weight = 10
identifier = "home"
url = "/"

  [languages.ja.menu.main.params]
  icon = "eva eva-home"

[[languages.ja.menu.main]]
name = "Archives"
weight = 40
identifier = "archives"
url = "/archives/"

  [languages.ja.menu.main.params]
  icon = "eva eva-bar-chart"

[[languages.ja.menu.main]]
name = "Search"
weight = 999
identifier = "search"
url = "/search/"

  [languages.ja.menu.main.params]
  icon = "eva eva-search"
